/* images */
import trompoRoll from "@/assets/bestSeller/trompoRoll.webp";
import arcoirisRoll from "@/assets/bestSeller/arcoirisRoll.webp";
import cheeseRoll from "@/assets/bestSeller/cheeseRoll.webp";
import clasicRoll from "@/assets/bestSeller/clasicRoll.webp";
import ninaFresaRoll from "@/assets/bestSeller/ninaFresaRoll.webp";
import { Product } from "@/types";

export const bestSellerProducts: Array<Product> = [
  {
    id: 1,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "bebidas y postres",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 2,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 3,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Sushi",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 4,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Sushi",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 5,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Sushi",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
];

/* export const products: Array<Product> = [
  {
    id: 1,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados Especiales",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 2,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 3,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Especialidades YAMA",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 4,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 5,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
  {
    id: 6,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 7,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 8,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Especialidades YAMA",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 9,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 10,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
  {
    id: 11,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados Especiales",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 12,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 13,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Especialidades YAMA",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 14,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 15,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
  {
    id: 16,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados Especiales",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 17,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 18,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Especialidades YAMA",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 19,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 20,
    productName: "fabian Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
]; */

export const promos: Array<Product> = [
  // CLÁSICOS
  {
    id: 1,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino, surimi (Con alga por fuera).",
    category: "rollos",
    promo: true,
    price: 125,
    image: trompoRoll,
  },
  {
    id: 2,
    productName: "Surimi Roll",
    ingredients:
      "Queso crema, pepino, aguacate, surimi empanizado (Con alga por fuera).",
    category: "rollos",
    promo: true,
    price: 125,
    image: arcoirisRoll,
  },
  {
    id: 3,
    productName: "Surimi Yama",
    ingredients:
      "Queso crema, pepino, aguacate, surimi, chipotle (Con alga por fuera).",
    category: "rollos",
    promo: true,
    price: 125,
    image: ninaFresaRoll,
  },
  {
    id: 4,
    productName: "Hawaii Roll",
    ingredients: "Queso crema, pepino, piña, surimi (Con alga por fuera).",
    category: "rollos",
    promo: true,
    price: 125,
    image: clasicRoll,
  },
  {
    id: 5,
    productName: "Tampico Roll",
    ingredients: "Con pasta tampico (Con alga por fuera).",
    category: "rollos",
    promo: true,
    price: 125,
    image: cheeseRoll,
  },
  {
    id: 6,
    productName: "Gaby Roll",
    ingredients: "Aguacate, chipotle y pollo (Con alga por fuera).",
    category: "rollos",
    promo: true,
    price: 125,
    image: ninaFresaRoll,
  },

  // TRADICIONALES
  {
    id: 7,
    productName: "California",
    ingredients: "Queso crema, pepino, surimi, aguacate y ajonjolí.",
    category: "rollos",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 8,
    productName: "Banana Roll",
    ingredients: "Queso crema, pepino, surimi y plátano frito por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 9,
    productName: "Cheese Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "rollos",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 10,
    productName: "Avocado Roll",
    ingredients: "Queso crema, pepino, surimi y aguacate por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 11,
    productName: "California Vegetariano",
    ingredients: "Aguacate y ajonjolí.",
    category: "rollos",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 12,
    productName: "Nuez Roll",
    ingredients:
      "Surimi empanizado, pasta tampico y por fuera nuez y queso crema.",
    category: "rollos",
    promo: true,
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 13,
    productName: "Beef Maki",
    ingredients:
      "Queso crema, pepino, aguacate, chile toreado, fajita de res y ajonjolí por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 14,
    productName: "Candy Roll",
    ingredients:
      "Nugget de pasta tampico, masago, por fuera queso crema y plátano frito.",
    category: "rollos",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 15,
    productName: "Poncho Roll",
    ingredients: "Con fritura y salsa picosita.",
    category: "rollos",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 16,
    productName: "Nevado",
    ingredients: "Zanahoria dulce, aguacate y queso crema por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },

  // EMPANIZADOS
  {
    id: 17,
    productName: "Chiquis Roll",
    ingredients: "Queso crema por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 18,
    productName: "Navegante Roll",
    ingredients: "Con salsa tampico.",
    category: "rollos",
    promo: true,
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 19,
    productName: "Navegante Spice Roll",
    ingredients: "Con salsa tampico picosita.",
    category: "rollos",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 20,
    productName: "Smile Roll",
    ingredients: "Mango por dentro (disponible por temporada).",
    category: "rollos",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 21,
    productName: "Coco Roll",
    ingredients: "Con plátano por dentro.",
    category: "rollos",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 22,
    productName: "Mexican Roll",
    ingredients: "Chile serrano y aguacate por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: clasicRoll,
  },

  // EMPANIZADOS ESPECIALES
  {
    id: 23,
    productName: "Tender Roll",
    ingredients:
      "Fajita de pollo por dentro, aguacate, queso crema y manchego.",
    category: "rollos",
    promo: true,
    price: 150,
    image: arcoirisRoll,
  },
  {
    id: 24,
    productName: "Meat Roll",
    ingredients:
      "Sin alga, queso crema, manchego, por fuera pollo laminado y empanizado.",
    category: "rollos",
    promo: true,
    price: 150,
    image: ninaFresaRoll,
  },
  {
    id: 25,
    productName: "Mr. Maki",
    ingredients: "Queso crema, manchego, aguacate y salmón.",
    category: "rollos",
    promo: true,
    price: 150,
    image: ninaFresaRoll,
  },
  {
    id: 26,
    productName: "Maki Altamira",
    ingredients: "Queso crema, manchego, aguacate y camarón.",
    category: "rollos",
    promo: true,
    price: 150,
    image: cheeseRoll,
  },
  {
    id: 27,
    productName: "Eclipse Roll",
    ingredients: "Ostión ahumado, queso crema y aguacate.",
    category: "rollos",
    promo: true,
    price: 150,
    image: clasicRoll,
  },
  {
    id: 28,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, aguacate, manchego y piña.",
    category: "rollos",
    promo: true,
    price: 150,
    image: cheeseRoll,
  },

  // FRUTALES
  {
    id: 29,
    productName: "Manila Roll",
    ingredients:
      "Cereza, plátano frito y mango por fuera (Disponible por temporada).",
    category: "rollos",
    promo: true,
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 30,
    productName: "Kiwi Roll",
    ingredients: "Queso crema, fresa, cereza, mango y kiwi por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 31,
    productName: "Ichigo Roll",
    ingredients: "Manzana, mango, queso crema, fresa y almendra por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 32,
    productName: "Cherry",
    ingredients: "Queso crema, fresa, plátano y cereza por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 33,
    productName: "Niña Fresa",
    ingredients: "Queso crema, plátano, cereza, mango, y fresa.",
    category: "rollos",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 34,
    productName: "Oreo Roll",
    ingredients:
      "Fresa, plátano, mango, queso crema y la clásica galleta oreo por fuera.",
    category: "rollos",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
];

export const products: Array<Product> = [
  /* --- SECCIÓN: SUSHI Y ROLLOS --- */

  // CLÁSICOS
  {
    id: 1,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino, surimi (Con alga por fuera).",
    category: "rollos clasicos",
    promo: true,
    price: 125,
    image: trompoRoll,
  },
  {
    id: 2,
    productName: "Surimi Roll",
    ingredients:
      "Queso crema, pepino, aguacate, surimi empanizado (Con alga por fuera).",
    category: "rollos clasicos",
    promo: true,
    price: 125,
    image: arcoirisRoll,
  },
  {
    id: 3,
    productName: "Surimi Yama",
    ingredients:
      "Queso crema, pepino, aguacate, surimi, chipotle (Con alga por fuera).",
    category: "rollos clasicos",
    promo: true,
    price: 125,
    image: ninaFresaRoll,
  },
  {
    id: 4,
    productName: "Hawaii Roll",
    ingredients: "Queso crema, pepino, piña, surimi (Con alga por fuera).",
    category: "rollos clasicos",
    promo: true,
    price: 125,
    image: clasicRoll,
  },
  {
    id: 5,
    productName: "Tampico Roll",
    ingredients: "Con pasta tampico (Con alga por fuera).",
    category: "rollos clasicos",
    promo: true,
    price: 125,
    image: cheeseRoll,
  },
  {
    id: 6,
    productName: "Gaby Roll",
    ingredients: "Aguacate, chipotle y pollo (Con alga por fuera).",
    category: "rollos clasicos",
    promo: true,
    price: 125,
    image: ninaFresaRoll,
  },

  // TRADICIONALES
  {
    id: 7,
    productName: "California",
    ingredients: "Queso crema, pepino, surimi, aguacate y ajonjolí.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 8,
    productName: "Banana Roll",
    ingredients: "Queso crema, pepino, surimi y plátano frito por fuera.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 9,
    productName: "Cheese Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 10,
    productName: "Avocado Roll",
    ingredients: "Queso crema, pepino, surimi y aguacate por fuera.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 11,
    productName: "California Vegetariano",
    ingredients: "Aguacate y ajonjolí.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 12,
    productName: "Nuez Roll",
    ingredients:
      "Surimi empanizado, pasta tampico y por fuera nuez y queso crema.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 13,
    productName: "Beef Maki",
    ingredients:
      "Queso crema, pepino, aguacate, chile toreado, fajita de res y ajonjolí por fuera.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 14,
    productName: "Candy Roll",
    ingredients:
      "Nugget de pasta tampico, masago, por fuera queso crema y plátano frito.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 15,
    productName: "Poncho Roll",
    ingredients: "Con fritura y salsa picosita.",
    category: "rollos tradicionales",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 16,
    productName: "Nevado",
    ingredients: "Zanahoria dulce, aguacate y queso crema por fuera.",
    category: "rollos tradicional",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },

  // EMPANIZADOS
  {
    id: 17,
    productName: "Chiquis Roll",
    ingredients: "Queso crema por fuera.",
    category: "rollos empanizad",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 18,
    productName: "Navegante Roll",
    ingredients: "Con salsa tampico.",
    category: "rollos empanizados",
    promo: true,
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 19,
    productName: "Navegante Spice Roll",
    ingredients: "Con salsa tampico picosita.",
    category: "rollos empanizados",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 20,
    productName: "Smile Roll",
    ingredients: "Mango por dentro (disponible por temporada).",
    category: "rollos empanizados",
    promo: true,
    price: 130,
    image: clasicRoll,
  },
  {
    id: 21,
    productName: "Coco Roll",
    ingredients: "Con plátano por dentro.",
    category: "rollos empanizados",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 22,
    productName: "Mexican Roll",
    ingredients: "Chile serrano y aguacate por fuera.",
    category: "rollos empanizados",
    promo: true,
    price: 130,
    image: clasicRoll,
  },

  // EMPANIZADOS ESPECIALES
  {
    id: 23,
    productName: "Tender Roll",
    ingredients:
      "Fajita de pollo por dentro, aguacate, queso crema y manchego.",
    category: "rollos empanizados",
    promo: true,
    price: 150,
    image: arcoirisRoll,
  },
  {
    id: 24,
    productName: "Meat Roll",
    ingredients:
      "Sin alga, queso crema, manchego, por fuera pollo laminado y empanizado.",
    category: "rollos empanizados",
    promo: true,
    price: 150,
    image: ninaFresaRoll,
  },
  {
    id: 25,
    productName: "Mr. Maki",
    ingredients: "Queso crema, manchego, aguacate y salmón.",
    category: "rollos empanizados",
    promo: true,
    price: 150,
    image: ninaFresaRoll,
  },
  {
    id: 26,
    productName: "Maki Altamira",
    ingredients: "Queso crema, manchego, aguacate y camarón.",
    category: "rollos empanizados",
    promo: true,
    price: 150,
    image: cheeseRoll,
  },
  {
    id: 27,
    productName: "Eclipse Roll",
    ingredients: "Ostión ahumado, queso crema y aguacate.",
    category: "rollos empanizados",
    promo: true,
    price: 150,
    image: clasicRoll,
  },
  {
    id: 28,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, aguacate, manchego y piña.",
    category: "rollos empanizados ",
    promo: true,
    price: 150,
    image: cheeseRoll,
  },

  // FRUTALES
  {
    id: 29,
    productName: "Manila Roll",
    ingredients:
      "Cereza, plátano frito y mango por fuera (Disponible por temporada).",
    category: "rollos frutales",
    promo: true,
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 30,
    productName: "Kiwi Roll",
    ingredients: "Queso crema, fresa, cereza, mango y kiwi por fuera.",
    category: "rollos frutales",
    promo: true,
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 31,
    productName: "Ichigo Roll",
    ingredients: "Manzana, mango, queso crema, fresa y almendra por fuera.",
    category: "rollos frutales",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 32,
    productName: "Cherry",
    ingredients: "Queso crema, fresa, plátano y cereza por fuera.",
    category: "rollos frutales",
    promo: true,
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 33,
    productName: "Niña Fresa",
    ingredients: "Queso crema, plátano, cereza, mango, y fresa.",
    category: "rollos frutales",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 34,
    productName: "Oreo Roll",
    ingredients:
      "Fresa, plátano, mango, queso crema y la clásica galleta oreo por fuera.",
    category: "rollos frutales",
    promo: true,
    price: 130,
    image: cheeseRoll,
  },

  // ESPECIALIDADES (Ojo: estos suelen ser precio completo)
  {
    id: 35,
    productName: "Oyster Roll",
    ingredients:
      "Queso crema, pepino, aguacate, ostión ahumado y alga por fuera.",
    category: "rollos especialidades",
    price: 160,
    image: clasicRoll,
  },
  {
    id: 36,
    productName: "Ebi Philadelphia",
    ingredients:
      "Queso crema, pepino, aguacate, camarones empanizados y alga por fuera.",
    category: "rollos especialidades",
    price: 160,
    image: cheeseRoll,
  },
  {
    id: 37,
    productName: "Salmón Roll",
    ingredients: "Queso crema, pepino, aguacate, surimi, y salmón por fuera.",
    category: "rollos especialidades",
    price: 160,
    image: clasicRoll,
  },
  {
    id: 38,
    productName: "Camarón Roll",
    ingredients: "Queso crema, aguacate, surimi y camarón por fuera.",
    category: "rollos especialidades",
    price: 160,
    image: ninaFresaRoll,
  },
  {
    id: 39,
    productName: "Tokio Roll",
    ingredients: "Queso crema, pepino, surimi, aguacate y masago por fuera.",
    category: "rollos especialidades",
    price: 160,
    image: arcoirisRoll,
  },
  {
    id: 40,
    productName: "Kappa Roll",
    ingredients: "Queso crema, pollo teriyaki y capeado por fuera.",
    category: "rollos especialidades",
    price: 160,
    image: clasicRoll,
  },
  {
    id: 41,
    productName: "Philadelphia Roll",
    ingredients: "Queso crema, salmón y por fuera ajonjolí o masago.",
    category: "rollos especialidades",
    price: 160,
    image: arcoirisRoll,
  },
  {
    id: 42,
    productName: "Chipotle Roll",
    ingredients:
      "Surimi, chipotle empanizado, aguacate, queso crema y camarón por fuera.",
    category: "rollos especialidades",
    price: 160,
    image: cheeseRoll,
  },
  {
    id: 43,
    productName: "Nori Maki",
    ingredients:
      "Queso crema, surimi, pepino, masago, aguacate y kani por fuera.",
    category: "rollos especialidades",
    price: 160,
    image: clasicRoll,
  },

  // ESPECIALIDADES YAMA
  {
    id: 44,
    productName: "Special Gady Roll",
    ingredients: "Ostión ahumado, aguacate, queso crema, masago y tempura.",
    category: "rollos  especialidades yama",
    price: 180,
    image: ninaFresaRoll,
  },
  {
    id: 45,
    productName: "Salmón Spicy Yama",
    ingredients: "Queso crema, aguacate y salmón spicy por fuera.",
    category: "rollos especialidades yama",
    price: 180,
    image: ninaFresaRoll,
  },
  {
    id: 46,
    productName: "Arcoiris",
    ingredients: "Salmón, camarón, masago y aguacate.",
    category: "rollos especialidades yama",
    price: 180,
    image: clasicRoll,
  },
  {
    id: 47,
    productName: "Alex Roll",
    ingredients:
      "Empanizado con queso crema, manchego, surimi empanizado y queso manchego por fuera.",
    category: "rollos especialidades yama",
    price: 180,
    image: cheeseRoll,
  },
  {
    id: 48,
    productName: "Dragon Roll",
    ingredients:
      "Empanizado con aguacate, queso crema, manchego, surimi, masago y kanni.",
    category: "rollos especialidades yama",
    price: 180,
    image: clasicRoll,
  },
  {
    id: 49,
    productName: "Dream Team",
    ingredients:
      "Camarón, surimi, plátano frito, queso crema, manchego y empanizado al coco.",
    category: "rollos especialidades yama",
    price: 180,
    image: trompoRoll,
  },
  {
    id: 50,
    productName: "Maki Monterrey",
    ingredients:
      "Rollo empanizado y por dentro zanahoria dulce, queso crema, aguacate, arrachera y manchego.",
    category: "rollos especialidades yama",
    price: 180,
    image: ninaFresaRoll,
  },

  /* Entradas*/

  {
    id: 51,
    productName: "Kushiages",
    ingredients: "3 Banderillas de plátano con queso manchego.",
    category: "entradas",
    price: 80,
    image: arcoirisRoll,
  },
  {
    id: 52,
    productName: "Gyosas",
    ingredients: "5 Empanaditas de carne molida y repollo morado.",
    category: "entradas",
    price: 80,
    image: clasicRoll,
  },
  {
    id: 53,
    productName: "Rollo Primavera",
    ingredients: "3 Rollitos de verduras con pollo.",
    category: "entradas",
    price: 80,
    image: cheeseRoll,
  },
  {
    id: 54,
    productName: "Verduras Capeadas",
    ingredients: "Delicioso mix de verduras.",
    category: "entradas",
    price: 80,
    image: cheeseRoll,
  },
  {
    id: 55,
    productName: "Sushi Esferas",
    ingredients: "6 Piezas de arroz rellenas de queso.",
    category: "entradas",
    price: 90,
    image: cheeseRoll,
  },
  {
    id: 56,
    productName: "Ebi Banderilla",
    ingredients: "Camarón con queso crema.",
    category: "entradas",
    price: 70,
    image: ninaFresaRoll,
  },
  {
    id: 57,
    productName: "Tiras de Surimi",
    ingredients: "3 Tiras empanizadas con queso manchego.",
    category: "entradas",
    price: 75,
    image: clasicRoll,
  },
  {
    id: 58,
    productName: "Banderillas de Surimi",
    ingredients: "3 Banderillas empanizadas con queso manchego y surimi.",
    category: "entradas",
    price: 75,
    image: arcoirisRoll,
  },
  {
    id: 59,
    productName: "Pollo al Panko",
    ingredients: "Receta de Yama. 7 tiras de pollo.",
    category: "entradas",
    price: 200,
    image: cheeseRoll,
  },
  {
    id: 60,
    productName: "Sunomano Mixta",
    ingredients: "Pepino, vinagre preparado, kanni, salmón, ostión y camarón.",
    category: "ensalada",
    price: 150,
    image: clasicRoll,
  },
  {
    id: 61,
    productName: "Ensalada Yama",
    ingredients:
      "Pepino en forma de diamante, surimi, ajonjolí y vinagre preparado.",
    category: "ensalada",
    price: 80,
    image: ninaFresaRoll,
  },

  // RAMEN
  {
    id: 62,
    productName: "Sopa Imperial de Mariscos",
    ingredients:
      "Camarón, pescado y calamar, miso, fideo chino, cebolla y champiñones.",
    category: "ramen",
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 63,
    productName: "Miso Ramen",
    ingredients: "Pasta miso, res, zanahoria, ejote, germen y fideo chino.",
    category: "ramen",
    price: 120,
    image: cheeseRoll,
  },
  {
    id: 64,
    productName: "Tori Tamago",
    ingredients: "Verduras, pollo, huevo y fideo chino.",
    category: "ramen",
    price: 120,
    image: clasicRoll,
  },

  // Platillos
  {
    id: 65,
    productName: "Res en Salsa de Ostión",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 66,
    productName: "Chop Suey",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 130,
    image: ninaFresaRoll,
  },
  {
    id: 67,
    productName: "Pollo Sirasha",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 68,
    productName: "Pollo Piña",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 69,
    productName: "Fideo Chino con Res",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 140,
    image: clasicRoll,
  },
  {
    id: 70,
    productName: "Res con Acelgas",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 140,
    image: cheeseRoll,
  },
  {
    id: 71,
    productName: "Puerco Hoisin",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 130,
    image: trompoRoll,
  },
  {
    id: 72,
    productName: "Pollo Agridulce Yama",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 140,
    image: ninaFresaRoll,
  },
  {
    id: 73,
    productName: "Pollo Kung Pao",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 160,
    image: arcoirisRoll,
  },
  {
    id: 74,
    productName: "Chow Mein",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 150,
    image: clasicRoll,
  },
  {
    id: 75,
    productName: "Pollo Teriyaki",
    ingredients: "Porción individual de medio litro.",
    category: "guisos clasicos",
    price: 130,
    image: cheeseRoll,
  },

  // NOODLES
  {
    id: 76,
    productName: "Noodles de Pollo",
    ingredients: "Fideos estilo oriental con pollo.",
    category: "noodles",
    price: 130,
    image: cheeseRoll,
  },
  {
    id: 77,
    productName: "Noodles de Res",
    ingredients: "Fideos estilo oriental con res.",
    category: "noodles",
    price: 150,
    image: ninaFresaRoll,
  },
  {
    id: 78,
    productName: "Noodles de Camarón",
    ingredients: "Fideos estilo oriental con camarón.",
    category: "noodles",
    price: 160,
    image: clasicRoll,
  },
  {
    id: 79,
    productName: "Noodles Mixto",
    ingredients: "Fideos estilo oriental mixto.",
    category: "noodles",
    price: 170,
    image: ninaFresaRoll,
  },

  // TEPANYAKI & YAKIMESHI
  {
    id: 80,
    productName: "Tepanyaki Mar Mixto (Completa)",
    ingredients:
      "Combinación de verduras, calamar, camarón y pescado (3-4 personas).",
    category: "tepanyaki",
    price: 300,
    image: clasicRoll,
  },
  {
    id: 81,
    productName: "Tepanyaki Mixto (Completa)",
    ingredients:
      "Combinación de verduras sazonadas, res, pollo y camarón (3-4 personas).",
    category: "tepanyaki",
    price: 300,
    image: ninaFresaRoll,
  },
  {
    id: 82,
    productName: "Yakimeshi",
    ingredients: "Arroz frito con verduras y huevo frito.",
    category: "yakimeshi",
    price: 125,
    image: cheeseRoll,
  },
  {
    id: 83,
    productName: "Yakimeshi Mixto",
    ingredients: "Camarón, res y pollo.",
    category: "yakimeshi",
    price: 140,
    image: ninaFresaRoll,
  },
  {
    id: 84,
    productName: "Arroz Tokio",
    ingredients: "Salmón, camarón, kanni, ajo, brócoli.",
    category: "arroz",
    price: 155,
    image: arcoirisRoll,
  },
  {
    id: 85,
    productName: "Arroz con Pollo Teriyaki",
    ingredients: "Ingrediente extra +$10.",
    category: "arroz",
    price: 160,
    image: cheeseRoll,
  },

  /*  BARRAS (NIGIRI, ONIGIRI, TEMAKI)*/

  {
    id: 86,
    productName: "Nigiri Salmón (2 pzas)",
    ingredients: "Bocado de arroz con lámina de salmón.",
    category: "nigiri",
    price: 90,
    image: arcoirisRoll,
  },
  {
    id: 87,
    productName: "Nigiri Masago (2 pzas)",
    ingredients: "Bocado de arroz con masago.",
    category: "nigiri",
    price: 90,
    image: arcoirisRoll,
  },
  {
    id: 88,
    productName: "Nigiri Camarón (2 pzas)",
    ingredients: "Bocado de arroz con camarón.",
    category: "nigiri",
    price: 90,
    image: clasicRoll,
  },
  {
    id: 89,
    productName: "Nigiri Kanni (2 pzas)",
    ingredients: "Bocado de arroz con cangrejo.",
    category: "nigiri",
    price: 90,
    image: ninaFresaRoll,
  },
  {
    id: 90,
    productName: "Onigiri (2 pzas)",
    ingredients:
      "Triángulos de arroz. Relleno a elegir: Tampico, Spicy, Philadelphia.",
    category: "onigiri",
    price: 90,
    image: clasicRoll,
  },
  {
    id: 91,
    productName: "Temaki Salmón",
    ingredients: "Cono de alga relleno de arroz y salmón.",
    category: "temaki",
    price: 105,
    image: trompoRoll,
  },
  {
    id: 92,
    productName: "Temaki Kani",
    ingredients: "Cono de alga relleno de arroz y cangrejo.",
    category: "temaki",
    price: 95,
    image: cheeseRoll,
  },
  {
    id: 93,
    productName: "Temaki Camarón",
    ingredients: "Cono de alga relleno de arroz y camarón.",
    category: "temaki",
    price: 105,
    image: ninaFresaRoll,
  },
  {
    id: 94,
    productName: "Temaki Surimi",
    ingredients: "Cono de alga relleno de arroz y Surimi.",
    category: "temaki",
    price: 105,
    image: ninaFresaRoll,
  },
  {
    id: 95,
    productName: "Temaki Masago",
    ingredients: "Cono de alga relleno de arroz y Masago.",
    category: "temaki",
    price: 105,
    image: ninaFresaRoll,
  },
  {
    id: 96,
    productName: "Temaki Ostion",
    ingredients: "Cono de alga relleno de arroz y Ostion.",
    category: "temaki",
    price: 105,
    image: ninaFresaRoll,
  },
  /* Bebidas Y Postres */

  {
    id: 97,
    productName: "Té Verde",
    ingredients: "500 ml.",
    category: "bebidas",
    price: 30,
    image: cheeseRoll,
  },
  {
    id: 98,
    productName: "Refresco",
    ingredients: "500 ml.",
    category: "bebidas",
    price: 40,
    image: arcoirisRoll,
  },
  {
    id: 99,
    productName: "Coca-Cola",
    ingredients: "355 ml.",
    category: "bebidas",
    price: 35,
    image: cheeseRoll,
  },
  {
    id: 100,
    productName: "Boing",
    ingredients: "De mango o guayaba.",
    category: "bebidas",
    price: 25,
    image: ninaFresaRoll,
  },
  {
    id: 101,
    productName: "Banana Yama (Postre)",
    ingredients: "Plátano frito y manchego.",
    category: "postres", // Lo puse en bebidas y postres para que salga en "Otros" o Postres
    price: 65,
    image: trompoRoll,
  },
];
