/* images */
import trompoRoll from "@/assets/bestSeller/trompoRoll.webp";
import arcoirisRoll from "@/assets/bestSeller/arcoirisRoll.webp";
import cheeseRoll from "@/assets/bestSeller/cheeseRoll.webp";
import clasicRoll from "@/assets/bestSeller/clasicRoll.webp";
import ninaFresaRoll from "@/assets/bestSeller/ninaFresaRoll.webp";
import { Product } from "@/types";

export const bestSellerProducts: Array<Product> = [
  {
    id: 1,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Bebidas",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 2,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 3,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Sushi",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 4,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Sushi",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 5,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Sushi",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
];

export const products: Array<Product> = [
  {
    id: 1,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados Especiales",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 2,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 3,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Especialidades YAMA",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 4,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 5,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
  {
    id: 6,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 7,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 8,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Especialidades YAMA",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 9,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 10,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
  {
    id: 11,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados Especiales",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 12,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 13,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Especialidades YAMA",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 14,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 15,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
  {
    id: 16,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados Especiales",
    promo: true,
    price: 130,
    image: trompoRoll,
  },
  {
    id: 17,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 18,
    productName: "Arcoiris Roll",
    ingredients: "Salmón, camarón, masago, y aguacate.",
    category: "Especialidades YAMA",
    price: 130,
    image: arcoirisRoll,
  },
  {
    id: 19,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 20,
    productName: "fabian Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
];

export const promos: Array<Product> = [
  {
    id: 1,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados Especiales",
    price: 130,
    image: trompoRoll,
    promo: true,
  },
  {
    id: 2,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
  {
    id: 3,
    productName: "Classic Roll",
    ingredients: "Queso crema, pepino y surimi",
    category: "Clásicos (con alga por afuera)",
    price: 130,
    image: clasicRoll,
    promo: true,
  },
  {
    id: 4,
    productName: "Chesse Roll",
    ingredients:
      "Chile serrano, queso manchego, queso crema, surimi y aguacate.",
    category: "Tradicionales",
    price: 130,
    image: cheeseRoll,
    promo: true,
  },
  {
    id: 5,
    productName: "Trompo Roll",
    ingredients: "Carne al pastor, piña, queso, manchego, y aguacate.",
    category: "Empanizados Especiales",
    price: 130,
    image: trompoRoll,
    promo: true,
  },
  {
    id: 6,
    productName: "Niña Fresa Roll",
    ingredients: "Queso crema, plátano, cereza mango y fresa.",
    category: "Frutales",
    price: 130,
    image: ninaFresaRoll,
    promo: true,
  },
];
